### ISSUE TITLE
Mirja Block - Genericness of end of charter

### ISSUE THREAD

**Issue by jimsch** [cbor-wg/charter#7]
2) I find the later part of the charter rather generic (starting which "There are a number of additional CBOR tagged types..."). I also don't really understand the difference of "General purpose" and "Internet-wide". These are two different aspects for me that don't exclude each other. I would rather like to see a charter that actually limits the technical scope rather than talking about a generic process (that may or could be or is applied in other groups as well).

**Comment by fpalombini** [comment]
Mirja's proposal: replace the generic part of the charter ("There are a number of additional CBOR tagged types...") with something on the lines of:

"The working group will evaluate such proposal individually and decide about addition of a respective milestone. Proposals that are deemed to be out of scope for the working group, e.g. because they are too narrow purpose specifications, may still be published as individual submission or in another groups if there is a specific need. The cbor group will review these proposals on request.”
